### ISSUE TITLE
Generate a Windows installer

### ISSUE THREAD

**Issue by deekayen** [binaryphile/minimak#4]
http://msdn.microsoft.com/en-us/goglobal/bb964665.aspx is a nice tool from Microsoft, which I used easily and quickly, to make the installer for the Norman layout. It seems more legit than the .reg files you're distributing and much cleaner than the PKL stuff.

**Comment by binaryphile** [comment]
Hey,

Thanks for the input.  What's available is what I've decided to use for my own purposes, which is both .reg and PKL, as well as whatever anyone else has decided to contribute (linux, macos).  I'm not opposed to the MKLC layout method, it just didn't work for me.  You can see my note on it at the end of the download page.

If you or anyone else would like to create the layouts in MKLC, I'd be happy to include them in the distribution.

I also meant to ask, since I didn't before...I assume the icons you contributed before are free of licensing concerns?  Are they covered by a particular license?  I like to keep up on those things.  Thanks.

Finally I wanted to mention something you might find interesting.  You mention the expense of TypeMatrix keyboards when discussing Workman on your site.  I wondered if you know they make a very affordable $60 version, the 2020.  I'm a value shopper as well, and I found it cheap enough to buy a couple for my machines at that price.  There's a link to it on the caveats page on my site, near the bottom.

I'll leave this issue open as a "please contribute MKLC layouts" item, but someone else will have to take it up.

Thanks!

**Comment by deekayen** [comment]
My license on the icns files is "these icons are my gift to you" to license however you want. You can claim you created them and copyright for all I care.

I had a 2020 a couple years ago and sold it on ebay. I think their updated version improves the design, but I'm both unwilling to pay that much or have anything more than a power cord plugged into my macbook.
